language: java
jdk:
  - oraclejdk7

branches:
  except:
    - /^fix-.*$/
    - /^fix_.*$/
    - /^dev_.*$/
    - /^dev_.*$/
  
before_script: mvn install
script: mvn deploy -P deploy.sonatype -DskipTests=true -X -s ./settings.xml

env:
  global:
    - secure: "f3Z/PHMNSPtaKb788/wtQiBe2y0z669UkWamsmQP12CDR/spUuDacBu1Cm9VqWr64uY24o0ckZ0dlE9sBegosV7dHvOFSkVDEPGnmeWfxIBSxF1r/wJ4RNH1XQAN18L1W8hM6J8y5LnlgriiRLEhHOzy3HvAQklduydvaILTa24="
    - secure: "IT91a9fdEVxj2G1CoCkeRqblTRK1PaTBkOiTSwmoj2JXd2J41h/Ta6FJdWU2Xs3D06Uf0pv6fqvWMjNxO2JaeirqA8+c5K2Md4HlbZ9hhH6jTbwmLuJEctnyLQfn8SRfAkCuMOsHbWy5lZHK3aIUD2WjiHsevMkZT7fcNMH9w7I="
  
notifications:
  email:
    recepients:
      - my-ava@yandex.ru
